/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.table;

import controller.PelamarController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class pelamaar extends javax.swing.JFrame {
   PelamarController controller;
    /**
     * Creates new form 
     */
    public pelamaar() {
         initComponents();
         getData();
         this.status("default");
    }
    
     private void getData() {
        DefaultTableModel model = (DefaultTableModel) table_pelamar.getModel();
        model.setRowCount(0);
         
        try{
            ResultSet rs = PelamarController.index();
            
            while(rs.next()){
                int id = rs.getInt("id");
                String nik = rs.getString("nik");
                String nama_pelamar = rs.getString("nama_pelamar");
                String nomer_telepon = rs.getString("nomer_telepon");
                String email = rs.getString("email");
                String status = rs.getString("status");
                Object[] rowData = {id,nik,nama_pelamar, nomer_telepon,email,status};
                model.addRow(rowData); // buat menambah row data di tabe
            }
            //Object[] rowData = {1,"dua","tiga","empat"};
            //model.addRow(rowData);
            rs.close(); // statement close
        }catch(Exception e){
             Logger.getLogger(pelamaar.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pelamar = new javax.swing.JTable();
        input_nik = new javax.swing.JTextField();
        label_nik = new javax.swing.JLabel();
        input_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        input_telepon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        input_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_status = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_pelamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "nik", "nama_pelamar", "nomer_telepon", "email", "status"
            }
        ));
        table_pelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pelamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pelamar);

        label_nik.setText("nik");

        jLabel2.setText("Nama");

        jLabel3.setText("Nomer telepon");

        jLabel4.setText("Email");

        jLabel5.setText("Status");

        btn_tambah.setText("tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_update.setText("update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jButton1.setText("back");

        jLabel1.setText("Table pelamar");

        jTextField1.setText("jTextField1");

        jButton2.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_nik)
                            .addComponent(input_nama)
                            .addComponent(input_telepon)
                            .addComponent(input_email)
                            .addComponent(input_status)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nik)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_tambah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_delete))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel1)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(label_nik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_status, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_update)
                    .addComponent(btn_delete))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String nik = input_nik.getText(); // get input
        String nama = input_nama.getText();
        String telepon = input_telepon.getText();
        String email = input_email.getText();
        String status = input_status.getText();
        
        if (nik.isEmpty() || nama.isEmpty() || telepon.isEmpty() || email.isEmpty() || status.isEmpty()){
            JOptionPane.showMessageDialog(this, "semua kolom harus disi", "validasi",JOptionPane.ERROR_MESSAGE); // buat erorr message
            return;
        }
        
        try{
            ArrayList<String> arr =  new  ArrayList<String>();
            arr.add(null);
            arr.add(nik);
            arr.add(nama);
            arr.add(email);
            arr.add(status);
            arr.add(telepon);
            arr.add(null);
            int result = PelamarController.insert(arr);
            if(result > 0 ){
                JOptionPane.showMessageDialog(this, "data berhasil di tambah");
                this.getData();
                this.resetform();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error input", "validasi",JOptionPane.ERROR_MESSAGE); // buat erorr message
            return;
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void table_pelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pelamarMouseClicked
        // TODO add your handling code here:
          this.status("disabled");
           int selectedRow = table_pelamar.getSelectedRow();
           String nik = table_pelamar.getValueAt(selectedRow, 1).toString();
           String nama = table_pelamar.getValueAt(selectedRow, 2).toString();
           String telepon = table_pelamar.getValueAt(selectedRow, 3).toString();
           String email  = table_pelamar.getValueAt(selectedRow, 4).toString();
           String Status = table_pelamar.getValueAt(selectedRow, 5).toString();
           input_nik.setText(nik);
           input_nama.setText(nama);
           input_telepon.setText(telepon);
           input_email.setText(email);
           input_status.setText(Status);
    }//GEN-LAST:event_table_pelamarMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_pelamar.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan di perbaharui","Validasi",JOptionPane.ERROR_MESSAGE); // show erorr message
            return;
        }
        String id = table_pelamar.getValueAt(selectedRow, 0).toString();
        
         String nik = input_nik.getText(); // get input
        String nama = input_nama.getText();
        String telepon = input_telepon.getText();
        String email = input_email.getText();
        String status = input_status.getText();
        
        if (nik.isEmpty() || nama.isEmpty() || telepon.isEmpty() || email.isEmpty() || status.isEmpty()){
            JOptionPane.showMessageDialog(this, "semua kolom harus disi", "validasi",JOptionPane.ERROR_MESSAGE); // buat erorr message
            return;
        }
        try{
            ArrayList<String> arr =  new  ArrayList<String>();
            arr.add(nik);
            arr.add(nama);
            arr.add(telepon);
            arr.add(email);
            arr.add(status);
            int result = PelamarController.update(arr , Integer.parseInt(id));
            if(result > 0 ){
                JOptionPane.showMessageDialog(this, "data berhasil di update");
                this.getData();
                this.resetform();
               this.status("enabled");
            }
        }catch(Exception E){
          JOptionPane.showMessageDialog(this, "error input", "validasi",JOptionPane.ERROR_MESSAGE); // buat erorr message
           return;
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_pelamar.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan di perbaharui","Validasi",JOptionPane.ERROR_MESSAGE); // show erorr message
            return;
        }
        String id = table_pelamar.getValueAt(selectedRow, 0).toString();
        try{
         int result = PelamarController.delete(id);
         if(result > 0 ){
                JOptionPane.showMessageDialog(this, "data berhasil di delete");
                this.getData();
                this.resetform();
                this.status("enabled");
         }
        }catch(Exception E){
          JOptionPane.showMessageDialog(this, "error", "validasi",JOptionPane.ERROR_MESSAGE); // buat erorr message
           return;
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelamaar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelamaar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelamaar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelamaar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelamaar().setVisible(true);
            }
        });
    }
    
    public void resetform(){
        input_nik.setText("");
        input_nama.setText("");
        input_telepon.setText("");
        input_email.setText("");
        input_status.setText("");
    }
    
    private void status (String param){
        if(param == "disabled"){
          btn_update.setEnabled(true);
          btn_delete.setEnabled(true);
          btn_tambah.setEnabled(false);
        }else if(param == "enabled"){
          btn_update.setEnabled(false);
          btn_delete.setEnabled(false);
          btn_tambah.setEnabled(true);
        }else if(param == "default"){
           btn_update.setEnabled(false);
           btn_delete.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_nama;
    private javax.swing.JTextField input_nik;
    private javax.swing.JTextField input_status;
    private javax.swing.JTextField input_telepon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_nik;
    private javax.swing.JTable table_pelamar;
    // End of variables declaration//GEN-END:variables
}
