/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.page.pelamar;

import Session.AuthSession;
import java.sql.SQLException;

/**
 *
 * @author LOQ
 */
public class home extends javax.swing.JFrame {
    private AuthSession session;
    /**
     * Creates new form home
     */
    public home(AuthSession session) throws SQLException {
        initComponents();
        this.session = session;
        label_ob.setText("Selamat datang "+ session.Pelamars().getNama_pelamar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_ob = new javax.swing.JLabel();
        option_2 = new javax.swing.JButton();
        option_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        label_ob.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_ob.setText("Selamat datang {NAME}");

        option_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        option_2.setText("Status Penerimaan");
        option_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_2ActionPerformed(evt);
            }
        });

        option_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        option_1.setText("Mencari Kerja");
        option_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_ob)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(option_1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option_2)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(label_ob)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_2ActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
         list_status p = new list_status(session);
         p.setVisible(true);
    }//GEN-LAST:event_option_2ActionPerformed

    private void option_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option_1ActionPerformed
        // TODO add your handling code here:
          this.setVisible(false);
         list_lamaran p = new list_lamaran(session);
         p.setVisible(true);
    }//GEN-LAST:event_option_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_ob;
    private javax.swing.JButton option_1;
    private javax.swing.JButton option_2;
    // End of variables declaration//GEN-END:variables
}
